=== WiReSEP/Rollercoaster2011/prototype/xml-schema-rollercoaster.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="RollerCoaster" targetNamespace="xml-schema-rollercoaster.xsd" elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns="xml-schema-rollercoaster.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="RollerCoaster">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Track" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Track">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="General" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="SimulationParameters" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="PillarList" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
     </xs:complexType>
  </xs:element>
  <xs:element name="General">
    <xs:complexType>
      <xs:sequence>
           <xs:element name="Name" type="xs:string" minOccurs="1" maxOccurs="1"/>
           <xs:element name="Author" type="xs:string" minOccurs="1" maxOccurs="1"/>
           <xs:element name="CreationDate" type="xs:string" minOccurs="1" maxOccurs="1"/>
           <xs:element name="Length" type="xs:double" minOccurs="1" maxOccurs="1"/>
           <xs:element name="Comment" type="xs:string" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
   <xs:element name="SimulationParameters">
    <xs:complexType>
      <xs:sequence>
           <xs:element name="Speed" type="xs:double" minOccurs="1" maxOccurs="1"/>
           <xs:element name="Scale" type="xs:double" minOccurs="1" maxOccurs="1"/>
           <xs:element name="Direction" type="xs:string" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="PillarList">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Pillar" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Pillar">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="PosX" type="xs:double" minOccurs="1" maxOccurs="1"/>
        <xs:element name="PosY" type="xs:double" minOccurs="1" maxOccurs="1"/>
        <xs:element name="PosZ" type="xs:double" minOccurs="1" maxOccurs="1"/>
        <xs:element name="YawX" type="xs:double" minOccurs="1" maxOccurs="1"/>
        <xs:element name="YawY" type="xs:double" minOccurs="1" maxOccurs="1"/>
        <xs:element name="YawZ" type="xs:double" minOccurs="1" maxOccurs="1"/>
        <xs:element name="YawAngle" type="xs:double" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== WiReSEP/Rollercoaster2011/prototype/examples/colossos.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<RollerCoaster xmlns="xml-schema-rollercoaster.xsd" 
xsi:schemaLocation="xml-schema-rollercoaster.xsd xml-schema-rollercoaster.xsd"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<Track>
<General>
<Name/>
<Author/>
<CreationDate>2009-05-03T10:29:55</CreationDate>
<Length>0.0</Length>
<Comment/>
</General>
<SimulationParameters>
<Speed>1.0</Speed>
<Scale>1.0</Scale>
<Direction>forward</Direction>
</SimulationParameters>
<PillarList>
<Pillar>
<PosX>157.0</PosX>
<PosY>89.0</PosY>
<PosZ>60.0</PosZ>
<YawX>0.8067128070749199</YawX>
<YawY>-0.10849330377433435</YawY>
<YawZ>0.5808990014946084</YawZ>
<YawAngle>0</YawAngle>
</Pillar>
<Pillar>
<PosX>217.0</PosX>
<PosY>87.0</PosY>
<PosZ>0.0</PosZ>
<YawX>-0.02523077641160532</YawX>
<YawY>-1.0578461040004582E-4</YawY>
<YawZ>0.9996816476915458</YawZ>
<YawAngle>0</YawAngle>
</Pillar>
<Pillar>
<PosX>286.0</PosX>
<PosY>88.0</PosY>
<PosZ>45.0</PosZ>
<YawX>-0.031796662505406074</YawX>
<YawY>-5.109464254790301E-4</YawY>
<YawZ>0.9994942276908194</YawZ>
<YawAngle>0</YawAngle>
</Pillar>
<Pillar>
<PosX>335.0</PosX>
<PosY>88.0</PosY>
<PosZ>0.0</PosZ>
<YawX>0.18812727152447437</YawX>
<YawY>-0.00409443575252872</YawY>
<YawZ>0.9821361236125189</YawZ>
<YawAngle>0</YawAngle>
</Pillar>
<Pillar>
<PosX>384.0</PosX>
<PosY>87.0</PosY>
<PosZ>35.0</PosZ>
<YawX>-0.11989017140576631</YawX>
<YawY>-7.475304399565917E-4</YawY>
<YawZ>0.9927868794451997</YawZ>
<YawAngle>0</YawAngle>
</Pillar>
<Pillar>
<PosX>419.0</PosX>
<PosY>88.0</PosY>
<PosZ>0.0</PosZ>
<YawX>0.32327475739465156</YawX>
<YawY>-1.2320760605782978E-4</YawY>
<YawZ>0.9463051389754339</YawZ>
<YawAngle>0</YawAngle>
</Pillar>
<Pillar>
<PosX>455.0</PosX>
<PosY>88.0</PosY>
<PosZ>30.0</PosZ>
<YawX>-0.49244624338331977</YawX>
<YawY>0.552883019395774</YawY>
<YawZ>0.672173388525214</YawZ>
<YawAngle>36</YawAngle>
</Pillar>
<Pillar>
<PosX>486.0</PosX>
<PosY>98.0</PosY>
<PosZ>25.0</PosZ>
<YawX>-0.4194565152664844</YawX>
<YawY>0.7660639622006062</YawY>
<YawZ>0.48703412366897425</YawZ>
<YawAngle>56</YawAngle>
</Pillar>
<Pillar>
<PosX>492.0</PosX>
<PosY>123.0</PosY>
<PosZ>17.5</PosZ>
<YawX>-0.8125316989385054</YawX>
<YawY>0.18894126075179277</YawY>
<YawZ>0.5514466775723914</YawZ>
<YawAngle>56</YawAngle>
</Pillar>
<Pillar>
<PosX>491.0</PosX>
<PosY>147.0</PosY>
<PosZ>10.0</PosZ>
<YawX>-0.6795375765094802</YawX>
<YawY>-0.05940618730612235</YawY>
<YawZ>0.731231554995661</YawZ>
<YawAngle>36</YawAngle>
</Pillar>
<Pillar>
<PosX>464.0</PosX>
<PosY>158.0</PosY>
<PosZ>0.0</PosZ>
<YawX>0.0501818371356879</YawX>
<YawY>0.012626943602986366</YawY>
<YawZ>0.9986602743260263</YawZ>
<YawAngle>0</YawAngle>
</Pillar>
<Pillar>
<PosX>445.0</PosX>
<PosY>136.0</PosY>
<PosZ>10.0</PosZ>
<YawX>-0.41822445663065105</YawX>
<YawY>0.44456259623735195</YawY>
<YawZ>0.7921189316653794</YawZ>
<YawAngle>-36</YawAngle>
</Pillar>
<Pillar>
<PosX>414.0</PosX>
<PosY>116.0</PosY>
<PosZ>15.0</PosZ>
<YawX>0.12951367381320625</YawX>
<YawY>0.6166589786508798</YawY>
<YawZ>0.7765036460601199</YawZ>
<YawAngle>-36</YawAngle>
</Pillar>
<Pillar>
<PosX>341.0</PosX>
<PosY>116.0</PosY>
<PosZ>30.0</PosZ>
<YawX>-0.20629682663305934</YawX>
<YawY>0.014395678332673795</YawY>
<YawZ>0.9783835565699536</YawZ>
<YawAngle>0</YawAngle>
</Pillar>
<Pillar>
<PosX>288.0</PosX>
<PosY>119.0</PosY>
<PosZ>0.0</PosZ>
<YawX>-0.09362906959592003</YawX>
<YawY>-8.678908912464215E-4</YawY>
<YawZ>0.9956067718190769</YawZ>
<YawAngle>0</YawAngle>
</Pillar>
<Pillar>
<PosX>228.0</PosX>
<PosY>117.0</PosY>
<PosZ>25.0</PosZ>
<YawX>0.2691508959414436</YawX>
<YawY>0.29141607250508106</YawY>
<YawZ>0.917951233944174</YawZ>
<YawAngle>-17</YawAngle>
</Pillar>
<Pillar>
<PosX>174.0</PosX>
<PosY>128.0</PosY>
<PosZ>20.0</PosZ>
<YawX>0.23118146078552176</YawX>
<YawY>0.5860702613394719</YawY>
<YawZ>0.7765801832152012</YawZ>
<YawAngle>-37</YawAngle>
</Pillar>
<Pillar>
<PosX>167.0</PosX>
<PosY>163.0</PosY>
<PosZ>17.5</PosZ>
<YawX>0.5564283442535053</YawX>
<YawY>-0.2295801249695435</YawY>
<YawZ>0.798548974033698</YawZ>
<YawAngle>-37</YawAngle>
</Pillar>
<Pillar>
<PosX>194.0</PosX>
<PosY>182.0</PosY>
<PosZ>15.0</PosZ>
<YawX>0.19865792244335925</YawX>
<YawY>-0.5708730602979133</YawY>
<YawZ>0.7966423155196962</YawZ>
<YawAngle>-37</YawAngle>
</Pillar>
<Pillar>
<PosX>232.0</PosX>
<PosY>179.0</PosY>
<PosZ>13.0</PosZ>
<YawX>-0.3260079154836348</YawX>
<YawY>-0.5075788115046792</YawY>
<YawZ>0.7975478601021462</YawZ>
<YawAngle>-37</YawAngle>
</Pillar>
<Pillar>
<PosX>237.0</PosX>
<PosY>146.0</PosY>
<PosZ>11.0</PosZ>
<YawX>-0.5145845895169348</YawX>
<YawY>0.31415549295868594</YawY>
<YawZ>0.7978151580883712</YawZ>
<YawAngle>-37</YawAngle>
</Pillar>
<Pillar>
<PosX>196.0</PosX>
<PosY>127.0</PosY>
<PosZ>9.0</PosZ>
<YawX>-0.09920760275046785</YawX>
<YawY>0.5957761858716358</YawY>
<YawZ>0.796999741470944</YawZ>
<YawAngle>-37</YawAngle>
</Pillar>
<Pillar>
<PosX>164.0</PosX>
<PosY>143.0</PosY>
<PosZ>7.0</PosZ>
<YawX>0.5658745785018846</YawX>
<YawY>0.2066244622617772</YawY>
<YawZ>0.7981806142724501</YawZ>
<YawAngle>-37</YawAngle>
</Pillar>
<Pillar>
<PosX>169.0</PosX>
<PosY>190.0</PosY>
<PosZ>7.0</PosZ>
<YawX>0.3103216678632967</YawX>
<YawY>-0.009715202101552302</YawY>
<YawZ>0.9505819676927749</YawZ>
<YawAngle>-15</YawAngle>
</Pillar>
<Pillar>
<PosX>209.0</PosX>
<PosY>217.0</PosY>
<PosZ>0.0</PosZ>
<YawX>-0.2120501277984775</YawX>
<YawY>-0.1409276068462428</YawY>
<YawZ>0.96704402843368</YawZ>
<YawAngle>0</YawAngle>
</Pillar>
<Pillar>
<PosX>238.0</PosX>
<PosY>250.0</PosY>
<PosZ>20.0</PosZ>
<YawX>0.024788222984987646</YawX>
<YawY>0.04104666215101161</YawY>
<YawZ>0.9988496961642964</YawZ>
<YawAngle>0</YawAngle>
</Pillar>
<Pillar>
<PosX>258.0</PosX>
<PosY>287.0</PosY>
<PosZ>0.0</PosZ>
<YawX>0.04461642989148601</YawX>
<YawY>0.08596690164683723</YawY>
<YawZ>0.9952984808613852</YawZ>
<YawAngle>0</YawAngle>
</Pillar>
<Pillar>
<PosX>280.0</PosX>
<PosY>325.0</PosY>
<PosZ>15.0</PosZ>
<YawX>-0.0679296301485012</YawX>
<YawY>-0.09419125585037992</YawY>
<YawZ>0.9932338962546616</YawZ>
<YawAngle>0</YawAngle>
</Pillar>
<Pillar>
<PosX>293.0</PosX>
<PosY>352.0</PosY>
<PosZ>0.0</PosZ>
<YawX>-0.6017124341568272</YawX>
<YawY>0.23863736449706383</YawY>
<YawZ>0.7622298569637386</YawZ>
<YawAngle>35</YawAngle>
</Pillar>
<Pillar>
<PosX>271.0</PosX>
<PosY>386.0</PosY>
<PosZ>0.0</PosZ>
<YawX>-0.20658555421177108</YawX>
<YawY>-0.5400350545641927</YawY>
<YawZ>0.8158949372516445</YawZ>
<YawAngle>35</YawAngle>
</Pillar>
<Pillar>
<PosX>232.0</PosX>
<PosY>380.0</PosY>
<PosZ>0.0</PosZ>
<YawX>0.28652057875790793</YawX>
<YawY>-0.49717332449657836</YawY>
<YawZ>0.8189778039466353</YawZ>
<YawAngle>35</YawAngle>
</Pillar>
<Pillar>
<PosX>197.0</PosX>
<PosY>349.0</PosY>
<PosZ>0.0</PosZ>
<YawX>0.004480001689722641</YawX>
<YawY>0.005029968191571899</YawY>
<YawZ>0.9999773142451043</YawZ>
<YawAngle>0</YawAngle>
</Pillar>
<Pillar>
<PosX>173.0</PosX>
<PosY>315.0</PosY>
<PosZ>0.0</PosZ>
<YawX>-0.0019891139258700484</YawX>
<YawY>-0.003648279702962977</YawY>
<YawZ>0.9999913667032326</YawZ>
<YawAngle>0</YawAngle>
</Pillar>
<Pillar>
<PosX>151.0</PosX>
<PosY>269.0</PosY>
<PosZ>0.0</PosZ>
<YawX>0.004780639767396841</YawX>
<YawY>0.010740992900989937</YawY>
<YawZ>0.9999308858890774</YawZ>
<YawAngle>0</YawAngle>
</Pillar>
<Pillar>
<PosX>139.0</PosX>
<PosY>240.0</PosY>
<PosZ>0.0</PosZ>
<YawX>-0.02269871150935337</YawX>
<YawY>-0.06462325021515809</YawY>
<YawZ>0.9976515443918504</YawZ>
<YawAngle>0</YawAngle>
</Pillar>
<Pillar>
<PosX>132.0</PosX>
<PosY>217.0</PosY>
<PosZ>0.0</PosZ>
<YawX>0.09539383716997951</YawX>
<YawY>0.3705231003040607</YawY>
<YawZ>0.9239116018164587</YawZ>
<YawAngle>0</YawAngle>
</Pillar>
<Pillar>
<PosX>132.0</PosX>
<PosY>191.0</PosY>
<PosZ>20.0</PosZ>
<YawX>-0.037230459183100965</YawX>
<YawY>0.5090165936289454</YawY>
<YawZ>0.859951161589657</YawZ>
<YawAngle>0</YawAngle>
</Pillar>
<Pillar>
<PosX>139.0</PosX>
<PosY>114.0</PosY>
<PosZ>60.0</PosZ>
<YawX>-0.06557316914231409</YawX>
<YawY>0.4908847525081017</YawY>
<YawZ>0.8687533132274623</YawZ>
<YawAngle>0</YawAngle>
</Pillar>
</PillarList>
</Track>
</RollerCoaster>
